#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header

# Update package list
sudo apt update

# Install Nginx and allow HTTP traffic
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create the default HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx server block
nginx_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Save Nginx configuration to a file
echo "$nginx_config" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
