#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     a. Starts manage_my_process
#     b. Creates a file containings its PID in /var/run/my_process.pid
#     c. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     a. Stops manage_my_process
#     b. Deletes the file /var/run/my_process.pid
#     c. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     a. Stops manage_my_process
#     b. Deletes the file /var/run/my_process.pid
#     c. Starts manage_my_process
#     d. Creates a file containing its PID in /var/run/my_process.pid
#     e. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

PIDFILE=/var/run/my_process.pid

if [ "$1" = "start" ]; then
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo manage_my_process started
elif [ "$1" = "stop" ]; then
	pkill -SIGKILL -f ./manage_my_process
	rm "$PIDFILE"
	echo manage_my_process stopped
elif [ "$1" = "restart" ]; then
	pkill -SIGKILL -f ./manage_my_process
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo manage_my_process restarted
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
