# Use the official Apache image as the base image
FROM httpd:2.4

# Copy a custom HTML file containing "Hello Holberton" to the default web root directory
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80
EXPOSE 80
