#!/usr/bin/env bash

# Configure the container to run Nginx under the `nginx` user on port 8080

# Change the ownership of the Nginx configuration file and the default
# Nginx site configuration file to the `nginx` user.
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default

# Make the Nginx configuration file writable by the `nginx` user.
chmod u+rwx /etc/nginx/nginx.conf

# Modify the Nginx configuration file and the default Nginx site
# configuration file to change the user that Nginx runs as and the
# port that Nginx listens on.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default

# Kill any running instances of the Apache web server.
pkill apache2

# Start the Nginx web server as the `nginx` user.
su nginx service nginx restart
