#!/usr/bin/env bash
#Using what you did for task #1, make your fix short and sweet.sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
